#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory
rm -rf post* *.log proc* Py* log.* 0
cp -r 0.orig 0

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=`getApplication`
cr=$(sed -ne 's/^ *numberOfSubdomains\s*\([0-9]*\)\s*;.*$/\1/p' system/decomposeParDict)

runApplication setFields
runApplication decomposePar

echo "Running renumberMesh"
mpirun -np $cr renumberMesh -overwrite -parallel > log.renumberMesh

echo "Running $application on $cr cores and monitoring residuals and bounded variables"
pyFoamPlotRunner.py mpirun -np $cr $application -parallel 2>&1 > /dev/null

#------------------------------------------------------------------------------
